# Generated by Django 3.1.2 on 2022-02-10 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Phone', max_length=256)),
                ('price', models.IntegerField(default=999999)),
                ('image', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/DynaTAC8000X.jpg/220px-DynaTAC8000X.jpg', max_length=400)),
                ('release_date', models.DateField(default=datetime.date(1973, 4, 3))),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
